package com.google.android.gms.measurement.internal;

import android.content.Context;
import androidx.recyclerview.widget.ItemTouchHelper;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
/* compiled from: com.google.android.gms:play-services-measurement-impl@@17.3.0 */
/* loaded from: classes.dex */
public final class zzap {
    public static zzfc<Integer> zzae;
    public static zzfc<Integer> zzaf;
    public static zzfc<Integer> zzag;
    public static zzfc<Integer> zzah;
    public static zzfc<Long> zzai;
    public static zzfc<Boolean> zzaj;
    public static zzfc<String> zzak;
    public static zzfc<Long> zzal;
    public static zzfc<Integer> zzam;
    public static zzfc<Double> zzan;
    public static zzfc<Integer> zzao;
    public static zzfc<Integer> zzap;
    public static zzfc<Boolean> zzaq;
    public static zzfc<Boolean> zzar;
    public static zzfc<Boolean> zzas;
    public static zzfc<Boolean> zzat;
    public static zzfc<Boolean> zzau;
    public static zzfc<Boolean> zzav;
    public static zzfc<Boolean> zzaw;
    public static zzfc<Boolean> zzax;
    public static zzfc<Boolean> zzay;
    public static zzfc<Boolean> zzaz;
    public static zzfc<Boolean> zzba;
    public static zzfc<Boolean> zzbb;
    public static zzfc<Boolean> zzbc;
    public static zzfc<Boolean> zzbd;
    public static zzfc<Boolean> zzbe;
    public static zzfc<Boolean> zzbf;
    public static zzfc<Boolean> zzbg;
    public static zzfc<Boolean> zzbh;
    public static zzfc<Boolean> zzbi;
    public static zzfc<Boolean> zzbj;
    public static zzfc<Boolean> zzbk;
    public static zzfc<Boolean> zzbl;
    public static zzfc<Boolean> zzbm;
    public static zzfc<Boolean> zzbn;
    public static zzfc<Boolean> zzbo;
    public static zzfc<Boolean> zzbp;
    public static zzfc<Boolean> zzbq;
    public static zzfc<Boolean> zzbr;
    public static zzfc<Boolean> zzbs;
    public static zzfc<Boolean> zzbt;
    public static zzfc<Boolean> zzbu;
    public static zzfc<Boolean> zzbv;
    public static zzfc<Boolean> zzbw;
    public static zzfc<Boolean> zzbx;
    public static zzfc<Boolean> zzby;
    public static zzfc<Boolean> zzbz;
    public static zzfc<Boolean> zzca;
    public static zzfc<Boolean> zzcb;
    public static zzfc<Boolean> zzcc;
    public static zzfc<Boolean> zzcd;
    public static zzfc<Boolean> zzce;
    public static zzfc<Boolean> zzcf;
    public static zzfc<Boolean> zzcg;
    public static zzfc<Boolean> zzch;
    public static zzfc<Boolean> zzci;
    public static zzfc<Boolean> zzcj;
    public static zzfc<Boolean> zzck;
    public static zzfc<Boolean> zzcl;
    public static zzfc<Boolean> zzcm;
    public static zzfc<Boolean> zzcn;
    public static zzfc<Boolean> zzco;
    public static zzfc<Boolean> zzcp;
    public static zzfc<Boolean> zzcq;
    public static zzfc<Boolean> zzcr;
    public static zzfc<Boolean> zzcs;
    public static zzfc<Boolean> zzct;
    public static zzfc<Boolean> zzcu;
    public static zzfc<Boolean> zzcv;
    public static zzfc<Boolean> zzcw;
    public static zzfc<Boolean> zzcx;
    public static zzfc<Boolean> zzcy;
    public static zzfc<Boolean> zzcz;
    public static zzfc<Boolean> zzda;
    public static zzfc<Boolean> zzdb;
    public static zzfc<Boolean> zzdc;
    public static zzfc<Boolean> zzdd;
    public static zzfc<Boolean> zzde;
    public static zzfc<Boolean> zzdf;
    public static zzfc<Boolean> zzdg;
    public static zzfc<Boolean> zzdh;
    private static zzfc<Boolean> zzdk;
    private static zzfc<Boolean> zzdl;
    private static zzfc<Boolean> zzdm;
    private static List<zzfc<?>> zzdi = Collections.synchronizedList(new ArrayList());
    private static Set<zzfc<?>> zzdj = Collections.synchronizedSet(new HashSet());
    public static zzfc<Long> zza = zza("measurement.ad_id_cache_time", 10000L, 10000L, zzas.zza);
    public static zzfc<Long> zzb = zza("measurement.monitoring.sample_period_millis", 86400000L, 86400000L, zzar.zza);
    public static zzfc<Long> zzc = zza("measurement.config.cache_time", 86400000L, 3600000L, zzbn.zza);
    public static zzfc<String> zzd = zza("measurement.config.url_scheme", "https", "https", zzca.zza);
    public static zzfc<String> zze = zza("measurement.config.url_authority", "app-measurement.com", "app-measurement.com", zzcj.zza);
    public static zzfc<Integer> zzf = zza("measurement.upload.max_bundles", 100, 100, zzcw.zza);
    public static zzfc<Integer> zzg = zza("measurement.upload.max_batch_size", 65536, 65536, zzdf.zza);
    public static zzfc<Integer> zzh = zza("measurement.upload.max_bundle_size", 65536, 65536, zzds.zza);
    public static zzfc<Integer> zzi = zza("measurement.upload.max_events_per_bundle", 1000, 1000, zzeb.zza);
    public static zzfc<Integer> zzj = zza("measurement.upload.max_events_per_day", 100000, 100000, zzeo.zza);
    public static zzfc<Integer> zzk = zza("measurement.upload.max_error_events_per_day", 1000, 1000, zzau.zza);
    public static zzfc<Integer> zzl = zza("measurement.upload.max_public_events_per_day", 50000, 50000, zzbd.zza);
    public static zzfc<Integer> zzm = zza("measurement.upload.max_conversions_per_day", 10000, 10000, zzbf.zza);
    public static zzfc<Integer> zzn = zza("measurement.upload.max_realtime_events_per_day", 10, 10, zzbi.zza);
    public static zzfc<Integer> zzo = zza("measurement.store.max_stored_events_per_app", 100000, 100000, zzbh.zza);
    public static zzfc<String> zzp = zza("measurement.upload.url", "https://app-measurement.com/a", "https://app-measurement.com/a", zzbk.zza);
    public static zzfc<Long> zzq = zza("measurement.upload.backoff_period", 43200000L, 43200000L, zzbj.zza);
    public static zzfc<Long> zzr = zza("measurement.upload.window_interval", 3600000L, 3600000L, zzbm.zza);
    public static zzfc<Long> zzs = zza("measurement.upload.interval", 3600000L, 3600000L, zzbl.zza);
    public static zzfc<Long> zzt = zza("measurement.upload.realtime_upload_interval", 10000L, 10000L, zzbo.zza);
    public static zzfc<Long> zzu = zza("measurement.upload.debug_upload_interval", 1000L, 1000L, zzbq.zza);
    public static zzfc<Long> zzv = zza("measurement.upload.minimum_delay", 500L, 500L, zzbp.zza);
    public static zzfc<Long> zzw = zza("measurement.alarm_manager.minimum_interval", 60000L, 60000L, zzbs.zza);
    public static zzfc<Long> zzx = zza("measurement.upload.stale_data_deletion_interval", 86400000L, 86400000L, zzbr.zza);
    public static zzfc<Long> zzy = zza("measurement.upload.refresh_blacklisted_config_interval", 604800000L, 604800000L, zzbu.zza);
    public static zzfc<Long> zzz = zza("measurement.upload.initial_upload_delay_time", 15000L, 15000L, zzbt.zza);
    public static zzfc<Long> zzaa = zza("measurement.upload.retry_time", 1800000L, 1800000L, zzbw.zza);
    public static zzfc<Integer> zzab = zza("measurement.upload.retry_count", 6, 6, zzbv.zza);
    public static zzfc<Long> zzac = zza("measurement.upload.max_queue_time", 2419200000L, 2419200000L, zzby.zza);
    public static zzfc<Integer> zzad = zza("measurement.lifetimevalue.max_currency_tracked", 4, 4, zzbx.zza);

    public static Map<String, String> zza(Context context) {
        com.google.android.gms.internal.measurement.zzbx zza2 = com.google.android.gms.internal.measurement.zzbx.zza(context.getContentResolver(), com.google.android.gms.internal.measurement.zzcm.zza("com.google.android.gms.measurement"));
        return zza2 == null ? Collections.emptyMap() : zza2.zza();
    }

    private static <V> zzfc<V> zza(String str, V v, V v2, zzfa<V> zzfaVar) {
        zzfc<V> zzfcVar = new zzfc<>(str, v, v2, zzfaVar);
        zzdi.add(zzfcVar);
        return zzfcVar;
    }

    public static final /* synthetic */ Long zzde() {
        if (zzez.zza != null) {
            zzw zzwVar = zzez.zza;
        }
        return Long.valueOf(com.google.android.gms.internal.measurement.zzji.zzc());
    }

    static {
        Integer valueOf = Integer.valueOf((int) ItemTouchHelper.Callback.DEFAULT_DRAG_ANIMATION_DURATION);
        zzae = zza("measurement.audience.filter_result_max_count", valueOf, valueOf, zzbz.zza);
        zzaf = zza("measurement.upload.max_public_user_properties", 25, 25, null);
        zzag = zza("measurement.upload.max_event_name_cardinality", 500, 500, null);
        zzah = zza("measurement.upload.max_public_event_params", 25, 25, null);
        zzai = zza("measurement.service_client.idle_disconnect_millis", 5000L, 5000L, zzcc.zza);
        zzaj = zza("measurement.test.boolean_flag", false, false, zzcb.zza);
        zzak = zza("measurement.test.string_flag", "---", "---", zzce.zza);
        zzal = zza("measurement.test.long_flag", -1L, -1L, zzcd.zza);
        zzam = zza("measurement.test.int_flag", -2, -2, zzcg.zza);
        Double valueOf2 = Double.valueOf(-3.0d);
        zzan = zza("measurement.test.double_flag", valueOf2, valueOf2, zzcf.zza);
        zzao = zza("measurement.experiment.max_ids", 50, 50, zzci.zza);
        zzap = zza("measurement.max_bundles_per_iteration", 1, 1, zzch.zza);
        zzaq = zza("measurement.validation.internal_limits_internal_event_params", false, false, zzck.zza);
        zzar = zza("measurement.referrer.enable_logging_install_referrer_cmp_from_apk", true, true, zzcm.zza);
        zzas = zza("measurement.client.sessions.session_id_enabled", true, true, zzcl.zza);
        zzat = zza("measurement.service.sessions.session_number_enabled", true, true, zzco.zza);
        zzau = zza("measurement.client.sessions.background_sessions_enabled", true, true, zzcn.zza);
        zzav = zza("measurement.client.sessions.remove_expired_session_properties_enabled", true, true, zzcq.zza);
        zzaw = zza("measurement.service.sessions.session_number_backfill_enabled", true, true, zzcp.zza);
        zzax = zza("measurement.service.sessions.remove_disabled_session_number", true, true, zzcs.zza);
        zzay = zza("measurement.client.sessions.start_session_before_view_screen", true, true, zzcr.zza);
        zzaz = zza("measurement.client.sessions.check_on_startup", true, true, zzcu.zza);
        zzba = zza("measurement.collection.firebase_global_collection_flag_enabled", true, true, zzct.zza);
        zzbb = zza("measurement.collection.efficient_engagement_reporting_enabled_2", false, false, zzcv.zza);
        zzbc = zza("measurement.collection.redundant_engagement_removal_enabled", false, false, zzcy.zza);
        zzbd = zza("measurement.personalized_ads_signals_collection_enabled", true, true, zzcx.zza);
        zzbe = zza("measurement.personalized_ads_property_translation_enabled", true, true, zzda.zza);
        zzbf = zza("measurement.experiment.enable_experiment_reporting", true, true, zzcz.zza);
        zzbg = zza("measurement.collection.log_event_and_bundle_v2", true, true, zzdc.zza);
        zzbh = zza("measurement.quality.checksum", false, false, null);
        zzdk = zza("measurement.module.collection.conditionally_omit_admob_app_id", true, true, zzdb.zza);
        zzbi = zza("measurement.sdk.dynamite.use_dynamite3", false, false, zzde.zza);
        zzbj = zza("measurement.sdk.dynamite.allow_remote_dynamite", false, false, zzdd.zza);
        zzbk = zza("measurement.sdk.collection.validate_param_names_alphabetical", true, true, zzdg.zza);
        zzbl = zza("measurement.collection.event_safelist", true, true, zzdi.zza);
        zzbm = zza("measurement.service.audience.scoped_filters_v27", true, true, zzdh.zza);
        zzbn = zza("measurement.service.audience.session_scoped_event_aggregates", true, true, zzdk.zza);
        zzbo = zza("measurement.service.audience.session_scoped_user_engagement", true, true, zzdj.zza);
        zzbp = zza("measurement.service.audience.scoped_engagement_removal_when_session_expired", true, true, zzdm.zza);
        zzbq = zza("measurement.client.audience.scoped_engagement_removal_when_session_expired", true, true, zzdl.zza);
        zzbr = zza("measurement.service.audience.remove_disabled_session_scoped_user_engagement", false, false, zzdo.zza);
        zzbs = zza("measurement.service.audience.use_bundle_timestamp_for_property_filters", true, true, zzdn.zza);
        zzbt = zza("measurement.service.audience.fix_prepending_previous_sequence_timestamp", true, true, zzdq.zza);
        zzdl = zza("measurement.service.audience.invalidate_config_cache_after_app_unisntall", true, true, zzdp.zza);
        zzbu = zza("measurement.service.audience.fix_skip_audience_with_failed_filters", true, true, zzdr.zza);
        zzbv = zza("measurement.audience.use_bundle_end_timestamp_for_non_sequence_property_filters", false, false, zzdu.zza);
        zzbw = zza("measurement.audience.refresh_event_count_filters_timestamp", false, false, zzdt.zza);
        zzbx = zza("measurement.audience.use_bundle_timestamp_for_event_count_filters", false, false, zzdw.zza);
        zzby = zza("measurement.sdk.collection.retrieve_deeplink_from_bow_2", true, true, zzdv.zza);
        zzbz = zza("measurement.app_launch.event_ordering_fix", true, true, zzdy.zza);
        zzca = zza("measurement.sdk.collection.last_deep_link_referrer2", true, true, zzdx.zza);
        zzcb = zza("measurement.sdk.collection.last_deep_link_referrer_campaign2", false, false, zzea.zza);
        zzcc = zza("measurement.sdk.collection.last_gclid_from_referrer2", false, false, zzdz.zza);
        zzcd = zza("measurement.sdk.collection.worker_thread_referrer", true, true, zzec.zza);
        zzce = zza("measurement.sdk.collection.enable_extend_user_property_size", true, true, zzee.zza);
        zzcf = zza("measurement.upload.file_lock_state_check", false, false, zzed.zza);
        zzcg = zza("measurement.sampling.calculate_bundle_timestamp_before_sampling", true, true, zzeg.zza);
        zzch = zza("measurement.ga.ga_app_id", false, false, zzef.zza);
        zzci = zza("measurement.lifecycle.app_backgrounded_tracking", true, true, zzei.zza);
        zzcj = zza("measurement.lifecycle.app_in_background_parameter", false, false, zzeh.zza);
        zzck = zza("measurement.integration.disable_firebase_instance_id", false, false, zzek.zza);
        zzcl = zza("measurement.lifecycle.app_backgrounded_engagement", false, false, zzej.zza);
        zzcm = zza("measurement.service.fix_gmp_version", true, true, zzem.zza);
        zzcn = zza("measurement.collection.service.update_with_analytics_fix", false, false, zzel.zza);
        zzco = zza("measurement.service.disable_install_state_reporting", true, true, zzen.zza);
        zzcp = zza("measurement.service.use_appinfo_modified", false, false, zzeq.zza);
        zzcq = zza("measurement.client.firebase_feature_rollout.v1.enable", true, true, zzep.zza);
        zzcr = zza("measurement.client.sessions.check_on_reset_and_enable", false, false, zzes.zza);
        zzcs = zza("measurement.config.string.always_update_disk_on_set", true, true, zzer.zza);
        zzct = zza("measurement.scheduler.task_thread.cleanup_on_exit", false, false, zzeu.zza);
        zzcu = zza("measurement.upload.file_truncate_fix", false, false, zzet.zza);
        zzcv = zza("measurement.engagement_time_main_thread", true, true, zzew.zza);
        zzcw = zza("measurement.sdk.referrer.delayed_install_referrer_api", false, false, zzev.zza);
        zzcx = zza("measurement.logging.improved_messaging_q4_2019_client", true, true, zzey.zza);
        zzcy = zza("measurement.logging.improved_messaging_q4_2019_service", true, true, zzat.zza);
        zzcz = zza("measurement.gold.enhanced_ecommerce.format_logs", false, false, zzaw.zza);
        zzda = zza("measurement.gold.enhanced_ecommerce.nested_param_daily_event_count", false, false, zzav.zza);
        zzdb = zza("measurement.gold.enhanced_ecommerce.upload_nested_complex_events", false, false, zzay.zza);
        zzdc = zza("measurement.gold.enhanced_ecommerce.log_nested_complex_events", false, false, zzax.zza);
        zzdd = zza("measurement.gold.enhanced_ecommerce.updated_schema.client", false, false, zzba.zza);
        zzde = zza("measurement.gold.enhanced_ecommerce.updated_schema.service", false, false, zzaz.zza);
        zzdm = zza("measurement.collection.synthetic_data_mitigation", false, false, zzbc.zza);
        zzdf = zza("measurement.service.configurable_service_limits", false, false, zzbb.zza);
        zzdg = zza("measurement.client.configurable_service_limits", false, false, zzbe.zza);
        zzdh = zza("measurement.androidId.delete_feature", true, true, zzbg.zza);
    }
}
